### ISSUE TITLE
fix: typing errors with typescript 4.8

### ISSUE THREAD

**Issue by dargmuesli** [sindresorhus/camelcase-keys#97]
[Some typing](https://github.com/sindresorhus/camelcase-keys/blob/1082010f742c9f5b371a4e2e7f86e2faa28f4e41/index.d.ts#L49-L57) does not seem to work fine with typescript 4.8.2: https://github.com/maevsi/stomper/runs/8039281506?check_suite_focus=true#step:5:174

```
#14 23.69 node_modules/camelcase-keys/index.d.ts(49,44): error TS2344: Type 'T[P]' does not satisfy the constraint 'readonly any[] | Record<string, any>'.
#14 23.69   Type 'T[keyof T]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69     Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69       Type 'T[string]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69         Type 'T[string]' is not assignable to type 'readonly any[]'.
#14 23.69           Type 'T[keyof T]' is not assignable to type 'readonly any[]'.
#14 23.69             Type 'T[P]' is not assignable to type 'readonly any[]'.
#14 23.69               Type 'T[keyof T]' is not assignable to type 'readonly any[]'.
#14 23.69                 Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'readonly any[]'.
#14 23.69                   Type 'T[string]' is not assignable to type 'readonly any[]'.
#14 23.70 node_modules/camelcase-keys/index.d.ts(52,4): error TS2344: Type 'T[P]' does not satisfy the constraint 'readonly any[] | Record<string, any>'.
```

**Comment by sindresorhus** [comment]
// @Masa-Shin @g-plane

**Comment by Masa-Shin** [comment]
It seems that this occurs with older versions of camelcase-keys but I will look into it.

**Comment by Masa-Shin** [comment]
PR: https://github.com/sindresorhus/camelcase-keys/pull/98

**Comment by 5c077yP** [comment]
Hey 👋 thanks for this great project. I wonder if this fix could also be backported to v7 which still works with commonjs 🙈

**Comment by 5c077yP** [comment]
Hey here's the start of a PR https://github.com/sindresorhus/camelcase-keys/pull/128 ... but i believe i would need to create a v7 branch from the last v7 tag , but not entirely sure how to do that, or if you even want that 🙈 would still be lovely to discuss (maybe on the PR) if this is something that is even wanted
