### PR TITLE
Add support for TS4.8

### LINKED ISSUE #97: fix: typing errors with typescript 4.8
[Some typing](https://github.com/sindresorhus/camelcase-keys/blob/1082010f742c9f5b371a4e2e7f86e2faa28f4e41/index.d.ts#L49-L57) does not seem to work fine with typescript 4.8.2: https://github.com/maevsi/stomper/runs/8039281506?check_suite_focus=true#step:5:174

```
#14 23.69 node_modules/camelcase-keys/index.d.ts(49,44): error TS2344: Type 'T[P]' does not satisfy the constraint 'readonly any[] | Record<string, any>'.
#14 23.69   Type 'T[keyof T]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69     Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69       Type 'T[string]' is not assignable to type 'readonly any[] | Record<string, any>'.
#14 23.69         Type 'T[string]' is not assignable to type 'readonly any[]'.
#14 23.69           Type 'T[keyof T]' is not assignable to type 'readonly any[]'.
#14 23.69             Type 'T[P]' is not assignable to type 'readonly any[]'.
#14 23.69               Type 'T[keyof T]' is not assignable to type 'readonly any[]'.
#14 23.69                 Type 'T[string] | T[number] | T[symbol]' is not assignable to type 'readonly any[]'.
#14 23.69                   Type 'T[string]' is not assignable to type 'readonly any[]'.
#14 23.70 node_modules/camelcase-keys/index.d.ts(52,4): error TS2344: Type 'T[P]' does not satisfy the constraint 'readonly any[] | Record<string, any>'.
```

### PR DESCRIPTION
**Pull request by Masa-Shin**
- Fix typing
- update tsd to the version using TS4.8

The code was tested with both version  of tsd.

Fixes #97

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for fixing :)

**Review by slymullar2k50 — COMMENTED** [review]
Fix
